# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set the Ansible configuration environment variable
ENV['ANSIBLE_CONFIG'] = "/etc/ansible/ansible.cfg"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu14.04"
    config.ssh.forward_agent = true
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

   config.vm.network :public_network


    config.vm.define "master" do |master|
        master.vm.hostname = "salt-masterless"
        master.vm.network :private_network, ip: "192.168.33.200"
    end
end
